# Generated by Django 3.2.2 on 2021-05-20 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last updated.', verbose_name='updated at')),
                ('state', models.BooleanField(default=False, editable=False, help_text='Main object state.', verbose_name='main state')),
                ('substate', models.BooleanField(default=False, editable=False, help_text='Secondary object state.', verbose_name='secondary state')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=3)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User by the object was created.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User by which the object was last updated.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last updated.', verbose_name='updated at')),
                ('state', models.BooleanField(default=False, editable=False, help_text='Main object state.', verbose_name='main state')),
                ('substate', models.BooleanField(default=False, editable=False, help_text='Secondary object state.', verbose_name='secondary state')),
                ('name', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(to='books.Author')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User by the object was created.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User by which the object was last updated.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
