# Generated by Django 3.2.2 on 2021-05-18 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last updated.', verbose_name='updated at')),
                ('state', models.BooleanField(default=False, editable=False, help_text='Main object state.', verbose_name='main state')),
                ('substate', models.BooleanField(default=False, editable=False, help_text='Secondary object state.', verbose_name='secondary state')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User by the object was created.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User by which the object was last updated.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last updated.', verbose_name='updated at')),
                ('state', models.BooleanField(default=False, editable=False, help_text='Main object state.', verbose_name='main state')),
                ('substate', models.BooleanField(default=False, editable=False, help_text='Secondary object state.', verbose_name='secondary state')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User by the object was created.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='choice_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User by which the object was last updated.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='choice_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
