# Generated by Django 3.2.2 on 2021-05-18 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at', '-updated_at'], 'verbose_name': 'choice', 'verbose_name_plural': 'choices'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at', '-updated_at'], 'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AddField(
            model_name='question',
            name='count_choices',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('B', 'Blank'), ('1', 'One')], max_length=200),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.question'),
        ),
    ]
