# Generated by Django 3.2.2 on 2022-04-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210518_0626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examplemodel',
            options={'verbose_name': 'example', 'verbose_name_plural': 'examples'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('B', 'Blank'), ('1', 'One')], max_length=1),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
